services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: insurance
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: insurance_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - insurance_db_data:/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mock-catalog-service:
    image: mockserver/mockserver
    container_name: mockserver
    ports:
      - '1080:1080'
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/mockserver.json
    volumes:
      - type: bind
        source: .
        target: /config

volumes:
  insurance_db_data:
